export const resources = [
  {
    title: "Products",
    description: "List of all products available in the store.",
    color: "#F67E7F",
    icon: "🛒",
    path: "/products",
  },
  {
    title: "Carts",
    description: "Details of the shopping carts.",
    color: "#55B9B7",
    icon: "🛍️",
    path: "/carts",
  },
  {
    title: "Users",
    description: "Information about users and their accounts.",
    color: "#757BF3",
    icon: "👤",
    path: "/users",
  },
  {
    title: "Posts",
    description: "List of user posts, typically for a blog or forum.",
    color: "#F67CAB",
    icon: "📝",
    path: "/posts",
  },
  {
    title: "Comments",
    description: "User comments on posts, products, etc.",
    color: "#55B9B7",
    icon: "💬",
    path: "/comments",
  },
  {
    title: "Quotes",
    description: "Inspirational or famous quotes.",
    color: "#F67E7F",
    icon: "💬",
    path: "/quotes",
  },
  {
    title: "Todos",
    description: "List of user tasks to complete.",
    color: "#F67CAB",
    icon: "✅",
    path: "/todos",
  },
  {
    title: "Recipes",
    description: "List of cooking recipes.",
    color: "#757BF3",
    icon: "🍽️",
    path: "/recipes",
  },
  {
    title: "Image",
    description: "Image resource, could be a single image or gallery.",
    color: "#F67E7F",
    icon: "🖼️",
    path: "/image",
  },
  {
    title: "Auth",
    description: "Authentication-related information and endpoints.",
    color: "#55B9B7",
    icon: "🔑",
    path: "/auth",
  },
];
